import requests

class LocalAiService:
    '''Service class to interact with the local AI language model.'''

    def __init__(self, ai_model: str):
        '''Initialize the local AI service with the specified model.
        Args:
            ai_model (str): The name of the AI model to use (e.g., "gpt-3.5-turbo", "llama3.2").
        '''
        self.ai_model = ai_model
        self.base_url = "http://localhost:11434/api"

    def response_llm(self, prompt: str) -> str:
        '''Call the local language model with the given prompt and return the response.
        Args:
            prompt: The input prompt to send to the language model.
        Returns:
            The response generated by the language model.
        '''
        response = requests.post(
            f"{self.base_url}/generate",
            json={
                "model": self.ai_model,
                "prompt": prompt,
                "stream": False
            }
        )
        return response.json()["response"]
    
    def converse_llm(self, messages: list[dict]) -> str:
        '''Call the local language model with the conversation history and return the response.
        Args:
            messages: List of {"role": "user"|"assistant", "content": str}
        Returns:
            The response generated by the language model.
        '''
        response = requests.post(
            f"{self.base_url}/chat",
            json={
                "model": self.ai_model,
                "messages": messages,
                "stream": False
            }
        )
        return response.json()["message"]["content"]


# localaiservice = LocalAiService(ai_model="llama3.2")
# response = localaiservice.response_llm("Quelle est la capitale de la France ?")
# print(response)