import requests

SYSTEM_PROMPT_DEFAULT = (
    "Tu es un assistant IA serviable et précis. "
    "Réponds toujours dans la langue utilisée par l'utilisateur. "
    "Sois concis, factuel et honnête. "
    "Si tu ne sais pas, dis-le plutôt qu'inventer."
)

SYSTEM_PROMPT_RAG = (
    "Tu es un assistant expert. "
    "Réponds uniquement en te basant sur le contexte fourni ci-dessous. "
    "Si la réponse ne figure pas dans le contexte, indique-le clairement plutôt que d'inventer. "
    "Réponds dans la langue utilisée par l'utilisateur. Sois précis et concis.\n\n"
    "Contexte :\n{context}"
)

MAX_HISTORY_MESSAGES = 20  # garde les N derniers échanges (hors system)


class LocalAiService:
    '''Service class to interact with the local AI language model.'''

    def __init__(self, ai_model: str):
        self.ai_model = ai_model
        self.base_url = "http://localhost:11434/api"
        self.temperature = 0.7

    def set_model(self, model: str) -> None:
        self.ai_model = model

    def get_model(self) -> str:
        return self.ai_model

    # Modèles qui ne supportent pas le chat (embedding, vision-only, etc.)
    _EMBEDDING_KEYWORDS = ('embed', 'minilm', 'e5-', 'bge-')

    def list_models(self) -> list[str]:
        '''Return the list of chat-capable models available in Ollama (excludes embedding models).'''
        response = requests.get(f"{self.base_url}/tags")
        response.raise_for_status()
        return [
            m["name"] for m in response.json().get("models", [])
            if not any(kw in m["name"].lower() for kw in self._EMBEDDING_KEYWORDS)
        ]

    def pull_model_stream(self, model: str):
        '''Stream pull progress from Ollama as NDJSON lines.
        Yields bytes lines; the last line has {"status": "success"} or {"error": "..."}.
        '''
        import json as _json
        try:
            response = requests.post(
                f"{self.base_url}/pull",
                json={"model": model, "stream": True},
                stream=True,
                timeout=3600,
            )
            response.raise_for_status()
            for line in response.iter_lines():
                if line:
                    yield line + b"\n"
        except Exception as e:
            yield _json.dumps({"error": str(e)}).encode() + b"\n"

    def response_llm(self, prompt: str) -> str:
        '''Call the local language model with the given prompt and return the response.
        Args:
            prompt: The input prompt to send to the language model.
        Returns:
            The response generated by the language model.
        '''
        response = requests.post(
            f"{self.base_url}/generate",
            json={
                "model": self.ai_model,
                "prompt": prompt,
                "stream": False
            }
        )
        return response.json()["response"]
    
    def _raise_ollama_error(self, response) -> None:
        '''Lève une exception avec le message d\'erreur Ollama inclus dans le body.'''
        try:
            detail = response.json().get('error', response.text)
        except Exception:
            detail = response.text
        raise ValueError(f"Ollama {response.status_code}: {detail}")

    def converse_llm(self, messages: list[dict]) -> str:
        '''Call the local language model with the conversation history and return the response.'''
        system = {"role": "system", "content": SYSTEM_PROMPT_DEFAULT}
        trimmed = messages[-MAX_HISTORY_MESSAGES:]
        response = requests.post(
            f"{self.base_url}/chat",
            json={
                "model": self.ai_model,
                "messages": [system] + trimmed,
                "stream": False,
                "options": {"temperature": self.temperature},
            }
        )
        if not response.ok:
            self._raise_ollama_error(response)
        data = response.json()
        if "message" not in data:
            raise ValueError(f"Réponse inattendue d'Ollama : {data}")
        return data["message"]["content"]

    def converse_with_context(self, messages: list[dict], context: str) -> str:
        '''Call the local language model with the conversation history and a RAG context.'''
        system_message = {
            "role": "system",
            "content": SYSTEM_PROMPT_RAG.format(context=context),
        }
        trimmed = messages[-MAX_HISTORY_MESSAGES:]
        response = requests.post(
            f"{self.base_url}/chat",
            json={
                "model": self.ai_model,
                "messages": [system_message] + trimmed,
                "stream": False,
                "options": {"temperature": self.temperature},
            }
        )
        if not response.ok:
            self._raise_ollama_error(response)
        data = response.json()
        if "message" not in data:
            raise ValueError(f"Réponse inattendue d'Ollama : {data}")
        return data["message"]["content"]